import { reactive, watch } from 'vue'
import type { AppData, Course, Settings, Slot } from './types'
import { defaultSettings, seedCourses } from './lib/seed'

const KEY = 'myclass-data-v1'

const CAD_NOTE = '集中实训（第 2 周，白天全天）；如与实际安排不符可直接编辑本课程'

function buildCadSlots(weeks: number[]): Slot[] {
  return [1, 2, 3, 4, 5].map(day => ({ day, startSection: 1, endSection: 9, weeks: [...weeks], location: '' }))
}

/**
 * 一次性数据修补（针对电子线路CAD设计）：
 * 1) 最早版本没有任何时段 → 补第 2 周；
 * 2) 曾按"第 2-3 周"自动生成 → 修正为仅第 2 周（仅当数据未被手动编辑过，即与自动生成的特征完全一致）。
 */
function migrate(courses: Course[]): Course[] {
  const cad = courses.find(c => c.id === 'c-cad-2w')
  if (!cad) return courses
  if (cad.slots.length === 0) {
    cad.slots = buildCadSlots([2])
    cad.note = CAD_NOTE
    return courses
  }
  const autoGenerated =
    cad.slots.length === 5 &&
    [...cad.slots].sort((a, b) => a.day - b.day).map(s => s.day).join(',') === '1,2,3,4,5' &&
    cad.slots.every(s => s.startSection === 1 && s.endSection === 9 && s.location === '' && s.weeks.join(',') === '2,3')
  if (autoGenerated) {
    cad.slots = buildCadSlots([2])
    cad.note = CAD_NOTE
  }
  return courses
}

function load(): AppData {
  try {
    const raw = localStorage.getItem(KEY)
    if (raw) {
      const d = JSON.parse(raw) as AppData
      if (d && Array.isArray(d.courses) && d.settings) {
        d.settings = { ...defaultSettings(), ...d.settings }
        d.version = d.version || 1
        d.courses = migrate(d.courses)
        return d
      }
    }
  } catch {
    /* 数据损坏则回退种子数据 */
  }
  return { version: 1, courses: migrate(seedCourses()), settings: defaultSettings() }
}

function persist(data: AppData) {
  try {
    localStorage.setItem(KEY, JSON.stringify(data))
  } catch {
    /* 存储空间不足时忽略 */
  }
}

export const store = reactive<{ data: AppData }>({ data: load() })
watch(() => store.data, d => persist(d), { deep: true })

export function upsertCourse(c: Course) {
  const list = store.data.courses
  const i = list.findIndex(x => x.id === c.id)
  if (i >= 0) list[i] = c
  else list.push(c)
}

export function deleteCourse(id: string) {
  const i = store.data.courses.findIndex(x => x.id === id)
  if (i >= 0) store.data.courses.splice(i, 1)
}

/** 清空全部课程（给别人用自己的课表时先清空） */
export function clearCourses() {
  store.data.courses = []
}

/** 导入教务课表：替换教务课程，保留自定义事项（班会等） */
export function replaceJxfwCourses(courses: Course[]) {
  store.data.courses = [...store.data.courses.filter(c => c.type === 'custom'), ...courses]
}

export function replaceAllCourses(courses: Course[]) {
  store.data.courses = courses
}

export function updateSettings(patch: Partial<Settings>) {
  Object.assign(store.data.settings, patch)
}

export function resetSectionTimes() {
  store.data.settings.sectionTimes = defaultSettings().sectionTimes
}

export function exportData(): string {
  return JSON.stringify(store.data, null, 2)
}

export function importData(json: string) {
  const d = JSON.parse(json) as AppData
  if (!d || !Array.isArray(d.courses) || !d.settings) throw new Error('备份文件格式不正确')
  d.settings = { ...defaultSettings(), ...d.settings }
  d.version = d.version || 1
  store.data = d
}

export function newId(): string {
  try {
    if (crypto?.randomUUID) return crypto.randomUUID()
  } catch {
    /* fallback below */
  }
  return `c-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
}
